### ISSUE TITLE
Add a search bar in "See all Pets" page | Front End

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/my-pets#129]
### Objective
Add a search bar to look for specific pets (in case the user has a lot of created pets)

---

### Description
Having in mind that a user can create as many pets as it wants, is a good idea to include a search bar in the page where the pets will be shown so the user can look for those it needs

---

### Tasks
- [x] Create the component (if needed)
- [x] Refactor `Icon` component
- [x] Integrate component to the page
- [x] Integrate component to the endpoint
- [x] Add needed UT

---

### Ticket relationships
| Relationship | Involved tickets |
| :--- | :---: |
| Is child of | **none**
| In parent of | **none**
| Is related to | **none**
| Is blocked by | **none**
| It blocks |  **none**

**Comment by NicolasOmar** [comment]
Have in mind [this medium article](https://medium.com/nerd-for-tech/debouncing-throttling-in-javascript-d36ace200cea) for debounce and throttle techniques for search scenarios
