### ISSUE TITLE
Include an Icon for the app

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/my-pets#130]
### Objective
Add an App icon in several places, which one will be user's navigation to home page.

---

### Description
Understanding missing features for this page, I came to the conclusion it is a good time to include an icon represntative for the app, which will be used in:
- Tab display (replacing `Vite`)
- `Welcome` and `Login` pages
- At user's top navigation, on its left side, used as a point to return to `Welcome` page.

---

### Tasks
- [x] Update `Icon` component (if needed)
- [x] Integrate it in the `NavBar` as `Brand` section
- [x] Integrate it at the `Login` page
- [x] Integrate it at the `Welcome` page
- [x] Add needed UT

---

### Ticket relationships
| Relationship | Involved tickets |
| :--- | :---: |
| Is child of | **none**
| In parent of | **none**
| Is related to | **none**
| Is blocked by | **none**
| It blocks |  **none**
