### ISSUE TITLE
Create a Pet event | Front End

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/my-pets#131]
### Objective
Add a feature where the User will be able to add a new pet event

---

### Description
Now the User is able to add a manage its created pets, the next feature to include is add an event that will create a log or journal por each Pet. This story cover the UI to create that event.

---

### Tasks
- Research
  - [x] Investigate needed fields to create a meaningful event.
  - [x] Investigate about ways to create the UI (by a modal, a full-size UI or other alternative).
- Development
  - [x] Create the needed components to build the UI.
  - [x] Integrate the query to fetch Pet's needed data.
  - [x] Integrate the mutation to create the event.
  - [x] Add/update the needed UT.

---

### Ticket relationships
| Relationship | Involved tickets |
| :--- | :---: |
| Is child of | **none**
| In parent of | **none**
| Is related to | **none**
| Is blocked by | **none**
| It blocks |  **none**

---

### Technical notes
TBD
