### ISSUE TITLE
See pet's events in table/grid mode | Front End

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/my-pets#132]
### Objective
Add a feature where the User will be able to see the created events of each pet in a table/grid view

---

### Description
Now the User is able to create events for its pets, the next feature to include a table/grid view where the events will be shown in a new page.

---

### Tasks
- Research
  - [x] Investigate about table/grid view implementations from other sources to understand how can be included in the UI.
  - [x] Investigate about libararies that can be included in the project.
- Development
  - [x] Create the needed components to build the UI.
  - [x] Integrate the query to fetch event's data.
  - [x] Add/update the needed UT.

---

### Ticket relationships
| Relationship | Involved tickets |
| :--- | :---: |
| Is child of | **none**
| In parent of | **none**
| Is related to | **none**
| Is blocked by | **none**
| It blocks |  **none**

---

### Technical notes
TBD
