### ISSUE TITLE
Update a Pet's event | Front End

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/my-pets#133]
### Objective
Add a feature that allows the User to edit a pet event they created.

---

### Description
Now, the User can add an event for their pets, and the next feature will allow them to update the event they created. This story covers the UI related to the feature.

---

### Tasks
- Development
  - [x] Create the needed components to build the UI (try to use ReactiveBulma's implementation).
  - [x] Integrate the query to fetch the event's needed data.
  - [x] Integrate the mutation to update the event.
  - [x] Add/update the needed UT.
  - [x] Reduce [SonarCloud's existing issues](https://sonarcloud.io/project/issues?resolved=false&id=NicolasOmar_my-pets) to a minimum.

---

### Technical notes
TBD
