### ISSUE TITLE
Add localization

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/my-pets#27]
### Objective
Add posibility of display the app in different languages based on user's localization.

---

### Description
Having in mind I never worked on localization, I want to add the enhancement as a learning experience
In order to make a first implementation, the app should include an English and a Spanish version only.
Also, the user choice should be disabled for this first approach (the language will be setted based on user's location, with a default language).

---

### Tasks
- Research
  - [ ] Look for theory related to localization, how to include it in a React application and which are the best options.
- Development
  - [ ] Include the needed libraries.
  - [ ] Implement the language changes on each component.
  - [ ] Add needed UT related to the implementation

---

### Ticket relationships
| Relationship | Involved tickets |
| :--- | :---: |
| Is child of | **none**
| In parent of | **none**
| Is related to | **none**
| Is blocked by | **none**
| It blocks |  **none**

**Comment by NicolasOmar** [comment]
Closed due to its way of the new scope, it could be revived in the future.
