### ISSUE TITLE
Create a 'Widgets' framework structure

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/my-pets#30]
### Objective
Create the base structure to contain Widgets in User's home page and its first test Widget item

---

### Description
This story will enable the addition of the first widget for the User with fake data, which will list the number of created pets and its types

---

### Tasks
- Research
  - **none**
- Development
  - [ ] Create the needed atom-level components
  - [ ] Create the needed molecule-level components
  - [ ] Create the needed organism-level components
  - [ ] Create the Widget template to hold the list of widgets
  - [ ] Create the page-level component to hold a fake item
  - [ ] Update and improve unit tests related to the story

---

### Tickets
| Relationship | Involved tickets |
| :--- | :---: |
| Is child from | [#26](https://github.com/NicolasOmar/my-pets/issues/26)
| In parent of | **none**
| Is related to | **none**
| Is blocked by | **none**
| It blocks |  **none**

---

### Technical notes
In order to achieve the feature on a mantainable way, first I will have to adapt the home page for a new set of components which will contain several widgets-type cards, and then connect those cards with the related APIs created for each case.
Now, focusing on this card in particular, I will create the mentioned structure and prepare the connections for the first card (utility TBD)

The created widget will have the following features:
 - Will have a status when:
   -  There is no loaded data
   -  Is fetching data
   -  Data couldn't be fetched

Other features (like toggle visibility, change what subset of data is visible, change each widget size and position) will be added in the future (after v0.2 is fully released)
