### ISSUE TITLE
Create Widget to look created Pets and its composition | Front end

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/my-pets#32]
### Objective
Create the Widget to show created Pets to the User

---

### Description
This story will enable the first widget which will show the number of created Pets, as well as a series of colored labels with each Pet Type and its quantity.

---

### Tasks
- Research
  - **none**
- Development
  - [x] Add the configuration object (probabily in a JSON config file)
  - [x] Integrate the endpoint related to the feature and its response.
  - [ ] Add and try to improve unit tests related to the implementation

---

### Tickets
| Relationship | Involved tickets |
| :--- | :---: |
| Is child from | [#26](https://github.com/NicolasOmar/my-pets/issues/26)
| In parent of | **none**
| Is related to | [#30](https://github.com/NicolasOmar/my-pets/issues/30), [#26 BE](https://github.com/NicolasOmar/my-pets-api/issues/26)
| Is blocked by | **none**
| It blocks |  **none**

---

### Technical notes
In order to achieve the feature on a mantainable way, the created widget should have the following features:
 - Will have a status when:
   -  There is no loaded data
   -  Is fetching data
   -  Data couldn't be fetched

Other features (like toggle visibility, change what subset of data is visible, change each widget size and position) will be added in the future (after v0.2 is fully released)
