### ISSUE TITLE
Rethink roadmap after v0.2

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/my-pets#34]
### Objective
Work on discover new features after revision with client.

---

### Description
In the last presentation to the client (showing the achieved work on `v0.2`), we decided to change focus on roadmap, rethink the objectives for the app and work on a new one where the objectives are more aligned to client's needs.

---

### Tasks
- [x] Review client's feedback and enlist its needs
- [x] Make a analysis on discovered needs
- [x] Build a roadmap proposal
- [x] Present proposal to client
- [x] Update roadmap updates on project's details page
- [x] Add this update on other places (even new ones for better visibility)

---

### Ticket relationships
| Relationship | Involved tickets |
| :--- | :---: |
| Is child of | **none**
| In parent of | **none**
| Is related to | **none**
| Is blocked by | **none**
| It blocks |  **none**

**Comment by NicolasOmar** [comment]
Roadmap has been updated with new features, previously accepted by client.
There are possibilities to update it in the future case of new objectives or client requests
