### ISSUE TITLE
Review and solve dependencies vulnerabilities | Front End

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/my-pets#35]
### Objective
Audit repo's package dependencies and fix those with vulnerabilites.

---

### Description
After some time without working on the project, codebase's dependencies have being updated as well has new vulnerabilities arised.
To fix those possible security problems, the best approach is to solve it properly by executing `npm audit fix`, review the changes didn't broke expected behaviours and build process.
Also, is good to update `Codecov Github Action` from v1 to v3 due to discontinuation advice from Codecov itself.

---

### Tasks
- [x] Check repo's dependabot errors
- [x] Run npm audit and its fix (use --force flag if needed)
- [x] Check UT suite runs without new problems/errors
- [x] Check build process runs without new problems/errors
- [x] Check repo's runs without new problems/errors
- [x] Update Codecov Github Action to v3
- [x] Add a dependabot weekly job using Github Actions

---

### Ticket relationships
| Relationship | Involved tickets |
| :--- | :---: |
| Is child of | **none**
| In parent of | **none**
| Is related to | **none**
| Is blocked by | **none**
| It blocks |  **none**
