### ISSUE TITLE
Integrate Typescript | Front End

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/my-pets#403]
### Objective
Integrate Typescript technology into the project's code.

---

### Description
To revitalize the project and ease the development experience (after gathering new information from past and current projects), I decided to include Typescript as part of the repo's tech stack.

---

### Tasks
- Investigation
  - [x] Find the easiest way to include the technology on the repo.
  - [x] Sieze alternatives to update code to Typescript in components.
  - [x] Sieze alternatives to update code to Typescript in functions.
  - [x] Sieze alternatives to update code to Typescript in unit tests.
- Development
  - [x] Update the component's code to Typescript.
  - [x] Update the function's code to Typescript.
  - [x] Update unit test code to Typescript.

---

### Ticket relationships
| Relationship | Involved tickets |
| :--- | :---: |
| Is child of | **none**
| In parent of | **none**
| Is related to | **none**
| Is blocked by | **none**
| It blocks |  **none**

---

### Technical notes
TBD
