### ISSUE TITLE
Update repo's vulnerable packages | Front End

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/my-pets#47]
### Objective
Update all repository dependencies to last versions in order to reduce vulnerabilities at minimun.

---

### Description
After several months without any update, I want to give MyPets project a second wind by applying ReactiveBulma's learned lessons about project maintainment and work on a more sustained basis to add value at least in a regular way.

---

### Tasks
- [x] Update each dependency version
- [x] Test UT suite to run as before
- [x] Test Storybook suite to run as before
- [x] Test application main features to run as before

---

### Ticket relationships
| Relationship | Involved tickets |
| :--- | :---: |
| Is child of | **none**
| In parent of | **none**
| Is related to | **none**
| Is blocked by | **none**
| It blocks |  **none**

---

### Technical notes
None
