### ISSUE TITLE
Integrate learned tools for CD/CI process | Front End

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/my-pets#48]
### Objective
Add several tools to be run in repo's CD/CI pipelines and improve code security, quality and status visibility

---

### Description
After learned several lessons last months with ReactiveBulma (check issues [#19](https://github.com/NicolasOmar/reactive-bulma/issues/19) [#23](https://github.com/NicolasOmar/reactive-bulma/issues/23) and [#50](https://github.com/NicolasOmar/reactive-bulma/issues/50)), I want to include the new knowledge using several tools that will help my work by highlighting its possible improvements, vulnerabilities and display them publicly.

---

### Tasks
- [x] Integrate Codecov workflow for PRs and merges to `main` branch
- [x] Display Codecov badge as status on repo's README
- [x] Integrate SondCloud workflow for PRs and merges to `main` branch
- [x] Display SondCloud badge as status on repo's README
- [x] Integrate Snyk workflow for PRs and merges to `main` branch
- [x] Display Snyk badge as status on repo's README
- [x] Integrate Dependabot workflow as a weekly job for GitHub Actions and dependencies version checks.
- [x] Update README structure with `Status` and/or `Dependencies` sections

---

### Ticket relationships
| Relationship | Involved tickets |
| :--- | :---: |
| Is child of | **none**
| In parent of | **none**
| Is related to | **none**
| Is blocked by | **none**
| It blocks |  **none**

---

### Technical notes
