### ISSUE TITLE
Analyze move from Create-react-app to Vite

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/my-pets#50]
### Objective
Check technical feasibility for technology change from create-react-app to vite, and in a positive case, do the required work.

---

### Description
After some months without any activity and started working on tickets related to dependency updates and vulnerability patches, I looked for ways to work with tools that could help my future work to be done in less time and with fewer possible problems.
Here comes Vite, that despite existing other tools/frameworks like NextJs (which I want to learn in the future) or Remix among others, I want to give it a try to Vite and have an opinion based on research and decide if migrate is for the best.

---

### Tasks
- [x] Check on [Vite's page](https://vitejs.dev/) for features, instalation process and other useful documentation.
- [x] Look for articles, documentation or other kind of bibliography to find the good, the bad and ugly parts of a possible migration to Vita from create-react-app.
- [x] Create new Vite-flavored project
- [x] Migrate Storybook configuration to coexists with Vite
- [x] Migrate package dependencies and configurations
- [x] Migrate components (with its structure and tests)
- [x] Make tests work using [Vitest](https://vitest.dev/)
- [x] Check all functionality works as before
- [x] Change deployment configs before merge to avoid possible deployment errors

---

### Ticket relationships
| Relationship | Involved tickets |
| :--- | :---: |
| Is child of | **none**
| In parent of | **none**
| Is related to | **none**
| Is blocked by | **none**
| It blocks |  **none**

---

### Technical notes
Used documentation so far:
- [[Article] - Migrating from create-react-app to vite](https://cathalmacdonnacha.com/migrating-from-create-react-app-cra-to-vite)
- [[Article] - Create react app to Vite](https://www.robinwieruch.de/vite-create-react-app/)

**Comment by NicolasOmar** [comment]
I add the main link where I looked for knowledge in my work to migrate from CRA to Vite:
- [Getting started with Vite](https://vitejs.dev/guide/)
- [Configuring Vitest](https://vitest.dev/config/#include)
- [How to use Context on React instead Redux](https://react.dev/reference/react/useContext)
