### ISSUE TITLE
Work ok bugs-type issues workflow

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/my-pets#52]
### Objective
Create a workflow in this board to document every created bug.

---

### Description
Having in mind the system will include new testing strategies besides unit tests, the best way to maintain a good documentation process for the team, as well as the people who use it, is to create a workflow as much automated as possible to reduce unnecessary manual work and give more time to the team to be focused on the work itself.

---

### Tasks
- [x] Understand testing necessities and own workflows
- [x] Research ways to automate such work for the team
- [x] Research other type of tools outside the GitHub universe to improve testing work
- [x] Research about issue templates
- [x] Research about github actions to handle issue workflow.
- [x] Create an issue template for bug cases (based on tester's provided template)
- [x] Create a workflow which will handle those created bugs by the tester, asign it to the project for public display and assign it to the developer in charge

---

### Ticket relationships
| Relationship | Involved tickets |
| :--- | :---: |
| Is child of | **none**
| In parent of | **none**
| Is related to | **none**
| Is blocked by | **none**
| It blocks |  **none**

---

### Technical notes
None

**Comment by NicolasOmar** [comment]
Have in mind the following links for each step on issue/bug creation:
- Create a step when an issue is created with bug tag and [has to be assigned to repo's project](https://github.com/actions/add-to-project#example-usage-issue-opened-with-labels-bug-or-needs-triage)
- Create another step when that issue is created and [you need to assign it to the developer who will fix it](https://github.com/pozil/auto-assign-issue#working-with-issues)
