### ISSUE TITLE
Extend Storybook documentation

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/my-pets#60]
### Objective
Add documentation information to MyPets's storybook implementation for better developer experience

---

### Description
After studying about Storybook capabilities and its implementation on other projects, I want to add this knowledge to current stack in order to improve components documentation by storybook features

---

### Tasks
- [x] Add documentation for all atom-level components
- [x] Add documentation for all molecule-level components
- [x] Add documentation for all organism-level components
- [x] Add documentation for all template-level components

---

### Ticket relationships
| Relationship | Involved tickets |
| :--- | :---: |
| Is child of | **none**
| In parent of | **none**
| Is related to | **none**
| Is blocked by | **none**
| It blocks |  **none**
