### ISSUE TITLE
Create a "Settings" page

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/my-pets#63]
### Objective
Create a new page where the user will handle all its settings

---

### Description
In order to improve user navigation on future implemenations, the best solution is to create a `Settings` page where the user will be able to locate all its related settings

---

### Tasks
- Research:
  - [x] Investigate about settings page implementations.
  - [x] Think in a UI after understand research's findings.
- Development:
  - [x] Create the page
  - [x] Move all the settings to the created feature
  - [x] Create a `Settings` option where the user will go to the page

---

### Ticket relationships
| Relationship | Involved tickets |
| :--- | :---: |
| Is child of | **none**
| In parent of | **none**
| Is related to | **none**
| Is blocked by | **none**
| It blocks |  **none**
