### ISSUE TITLE
Check missing common properties for used components

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/my-pets#64]
### Objective
Check in every component it has several missing common properties.

---

### Description
In order to enhance each component customization in several areas beyond Bulma's capacities, I should review, include and test different properties like:
- `testId` for custom testing ids.
- `containerTestId` for custom testing ids in component's container.
- `style` for custom modifications that do not need any CSS classes.
- `containerStyle` for custom modifications that do not need any CSS classes in component's container.
- `cssClasses` for custom classes on the implemented component (for specific scenarios).
- `containerCssClasses` for custom classes on the implemented component's container(for specific scenarios).

---

### Tasks
- Add missing properties on:
  - [x] All atom-level components
  - [x] All molecule-level components
  - [x] All organism-level components
  - [x] All template-level components

---

### Ticket relationships
| Relationship | Involved tickets |
| :--- | :---: |
| Is child of | **none**
| In parent of | **none**
| Is related to | **none**
| Is blocked by | **none**
| It blocks |  **none**

---

### Technical notes
None

**Comment by NicolasOmar** [comment]
[JSDoc url](https://jsdoc.app/index.html) added to attach documentation for a tool that will help component's documentation
